#!/usr/bin/env bash
# Apply the firewall atomically as soon as it appears.
#
# The firewall files are generated by `iptables-save`/`ip6tables-save`
# in a separate container for building the firewall rules.
#

# Where to get the iptables dump files.
: ${IPTABLES_FILE_V4:="/tmp/iptables.txt"}
: ${IPTABLES_FILE_V6:="/tmp/ip6tables.txt"}

if [[ -e "${IPTABLES_FILE_V4}" ]]; then
  iptables-restore <"${IPTABLES_FILE_V4}"
  rm -f "${IPTABLES_FILE_V4}"
  echo "The firewall is applied (v4)."
fi

if [[ -e "${IPTABLES_FILE_V6}" ]]; then
  ip6tables-restore <"${IPTABLES_FILE_V6}"
  rm -f "${IPTABLES_FILE_V6}"
  echo "The firewall is applied (v6)."
fi
